name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    name: Release Please
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          token: ${{ github.token }}
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}

  publish:
    needs: release
    if: ${{ fromJSON(needs.release.outputs.releases_created) }}
    name: Publish
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          package-manager-cache: false
          node-version-file: package.json
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
